robot_base_position: [0.6, 0.0, 0.05]
up_axis_index: 2
## camera settings
render_width: 300
render_height: 300
cam_static_intrinsics:
  fx: 259.80761647
  fy: 259.80761647
  cx: 150.0
  cy: 150.0
cam_static_dist: 0.8
cam_static_yaw: -90
cam_static_pitch: -20 # 40
cam_static_target: [-0.25, 0.05, 0.5] # [-0.1, 0.05, 0.5] [0.15, 0.1, 0.15] [0.18, 0, 0.2]
cam_wrist_intrinsics:
  fx: 300.0
  fy: 300.0
  cx: 150.0
  cy: 150.0
cam_near: 0.001
cam_far: 10.0

translate_distance: 0.12
grasp_bbox_ext_ratio: 8.0
touch_bbox_ext_ratio: 1.2
translate_target_dis_thred: 0.15
translate_dir_norm_dis_thred: 0.1
rotate_target_dis_thred: 0.5
release_distance_tcp_z: -0.05
release_distance_world_z: 0.1
release_target_dis_thred: 0.125
release_target_rot_thred: 0.1

device: 'cuda:0'
## paths
data_root: /media/yyin34/ExtremePro/projects/partinstruct/code/part_instruct/data
meta_path: generated_episodes.json
scene_path: urdfs/scenes/stage_v3_sc0_staging.urdf
scene_config_path: null
objects_directory: null 
urdf_robot: urdfs/robots/franka_panda/panda.urdf
urdf_table: urdfs/wood/wood.urdf
urdf_floor: urdfs/floor/floor.urdf
partnet_path: partnet-grasping

shape_meta:
  obs:
    agentview_rgb:
      shape: [3, 300, 300]
      type: rgb
    gripper_state:
      shape: [1]
      type: low_dim
    joint_states: 
      shape: [7]
      type: low_dim
    tcp_pose: 
      shape: [7]
      type: low_dim
    instructions: 
      shape: [512]
      type: text
  action: 
    shape: [7]

## if specify object
obj_class: mug
obj_id: "8611"
obj_position: [0.03869500619942617, -0.031480762319536344, 0.11393329759108875]
# obj_position: [-0.042464047716708454, -0.02849420580107398, 0.09632049917220427]
skill_chain: "1"
chain_params:
- skill_name: grasp
  params:
    part_grasp: top
    region_on_part: right